/**
 * FILE CONSISTS OF ASYNCHRONOUS FUNCTIONS
 * TESTING THE ASYNCHRONOUS FUNCTIONS FOR
 * - RESPONSE
 * - RESPONSE TYPE
 * - NO RESPONSE
 * - INVALID REQUEST PAYLOAD
 * - INVALID ENDPOINT
 * - ERROR
 * */ 
